name: Linting

on: [push]

jobs:
    php-cs-fixer:
        name: 'Code Style Fixer'
        runs-on: ubuntu-latest
        steps:
            -   uses: actions/checkout@v2
            -   name: PHP-CS-Fixer
                uses: docker://oskarstark/php-cs-fixer-ga
                with:
                    args: --allow-risky=yes --dry-run -v
